name: agri_trade
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  get: 4.6.6
  iconsax: 0.0.8
  firebase_core: ^3.4.0
  firebase_auth: ^5.0.0
  firebase_storage:
  cloud_firestore:
  firebase_messaging: ^15.1.3
  flutter_local_notifications: ^17.2.3
  http:
  google_sign_in: ^5.0.0
  image_picker:
  cached_network_image: ^3.4.1
  flutter_stripe: ^11.2.0
  dio: ^5.7.0
  shared_preferences: ^2.3.2
  googleapis_auth: ^1.6.0
  intl: ^0.18.1
  fl_chart: ^0.69.2
  flutter_email_sender: ^6.0.3

dev_dependencies:
  flutter_launcher_icons: ^0.13.1  # Check for the latest version
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0



flutter:
  uses-material-design: true

  assets:
    - assets/font/
    - assets/brand_artworks/
    - assets/products/
#    - assets/icon/
    - assets/
  #   - images/a_dot_ham.jpeg
  # example:
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/font/Poppins-Regular.ttf

flutter_icons:
  android: true
  ios: true
  image_path: "assets/ic_logo_radius.png"